### ISSUE TITLE
Is inserting text possible too?

### ISSUE THREAD

**Issue by goswinr** [goswinr/AvalonLog#1]
_This is to follow up on_ https://github.com/icsharpcode/AvalonEdit/issues/303#issuecomment-912905700:

> I have roughly rewritten what I need to use, but I found a bug at present. If you insert a string in the middle of a string of multiple colors, it will cause the subsequent color display to be completely confused.

Is inserting text possible too?

**Comment by goswinr** [comment]
Short answer: no. The editor is intended for append only. But this could be an added feature in the future.

**Comment by dzx815** [comment]
Thanks for replying, I have solved this problem.

**Comment by goswinr** [comment]
Ah, good, Do you want to make a pull request?

**Comment by dzx815** [comment]
Sorry, I have been a bit busy recently. I have made some changes to the code piecemeal. The code is poorly written and I haven't had time to organize it. I implemented it with reference to this code[https://github.com/siegfriedpammer/AvalonEditSamples](AvalonEditSamples)，Almost all is based on this part of the code, the other is some simple optimizations, you can refer to it.
